### ISSUE TITLE
Support prettierx 0.19.0

### ISSUE THREAD

**Issue by shaylew** [aMarCruz/prettier#1]
Prettierx now has an 0.19.0 release, with changes from prettier 2.3.x included. Hopefully it'd be just a few version bumps to get that working here.

More ambitiously (and probably more annoying to implement): it would be great if this package could let users install their own `prettierx` version and make a best-effort attempt to work with whatever that version was. That way nobody who wants to get new features can set that up without having to wait on this adapter package to update.

**Comment by aMarCruz** [comment]
> More ambitiously (and probably more annoying to implement): it would be great if this package could let users install their own prettierx version and make a best-effort attempt to work with whatever that version was. That way nobody who wants to get new features can set that up without having to wait on this adapter package to update.

Right, I will make that.

**Comment by aMarCruz** [comment]
v2.4.0 is using `"prettierx": ">=0.19.0"`
